<?php

namespace ContainerAeuE1Sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MKU8NbhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MKU8Nbh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MKU8Nbh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Normalizer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'constatRepository' => ['privates', 'App\\Repository\\ConstatRepository', 'getConstatRepositoryService', true],
        ], [
            'Normalizer' => '?',
            'constatRepository' => 'App\\Repository\\ConstatRepository',
        ]);
    }
}
