<?php

namespace ContainerAeuE1Sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9vWqCnDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9vWqCnD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9vWqCnD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'constatRepository' => ['privates', 'App\\Repository\\ConstatRepository', 'getConstatRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'constatRepository' => 'App\\Repository\\ConstatRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
