<?php

namespace ContainerAeuE1Sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4aKLfKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4aKLf_K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4aKLf_K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'constat' => ['privates', '.errored..service_locator.4aKLf_K.App\\Entity\\Constat', NULL, 'Cannot autowire service ".service_locator.4aKLf_K": it references class "App\\Entity\\Constat" but no such service exists.'],
            'vehiculeRepository' => ['privates', 'App\\Repository\\VehiculeRepository', 'getVehiculeRepositoryService', true],
        ], [
            'constat' => 'App\\Entity\\Constat',
            'vehiculeRepository' => 'App\\Repository\\VehiculeRepository',
        ]);
    }
}
