<?php

namespace ContainerAeuE1Sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppCustomAuthentificatorAuthenticatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\AppCustomAuthentificatorAuthenticator' shared autowired service.
     *
     * @return \App\Security\AppCustomAuthentificatorAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['App\\Security\\AppCustomAuthentificatorAuthenticator'])) {
            return $container->privates['App\\Security\\AppCustomAuthentificatorAuthenticator'];
        }

        return $container->privates['App\\Security\\AppCustomAuthentificatorAuthenticator'] = new \App\Security\AppCustomAuthentificatorAuthenticator(($container->services['router'] ?? $container->getRouterService()), $a);
    }
}
