<?php

namespace ContainerAeuE1Sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConstatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4aKLf_K.App\Entity\Constat' shared service.
     *
     * @return \App\Entity\Constat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.4aKLf_K": it references class "App\\Entity\\Constat" but no such service exists.');
    }
}
