<?php

namespace ContainerAeuE1Sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehicule2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pB20uqv.App\Entity\Vehicule' shared service.
     *
     * @return \App\Entity\Vehicule
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.pB20uqv": it references class "App\\Entity\\Vehicule" but no such service exists.');
    }
}
