<?php

namespace ContainerAeuE1Sx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehiculeRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\VehiculeRepository' shared autowired service.
     *
     * @return \App\Repository\VehiculeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\VehiculeRepository'] = new \App\Repository\VehiculeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
