# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.path.product_images: /uploads/constat
    app.debug: true
    twilio_sid: <AC6bcc0a3decff237a4fea743cf6909a88>
    twilio_token: <37ac977c004c1cc9b6c18b3b2d87d4b9>
    twilio_number: <+12762901120>


services:
    twilio.client:
        class: Twilio\Rest\Client
        arguments: [ '%twilio_sid%', '%twilio_token%' ]

    # Ajoute un alias pour le service twilio.client
    Twilio\Rest\Client: '@twilio.client'
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
