vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: '/uploads/constat'
            upload_destination: '%kernel.project_dir%/public/uploads/constat'
            namer:  Vich\UploaderBundle\Naming\UniqidNamer

