<?php

namespace ContainerXFUFN6Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZUhtkMkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zUhtkMk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zUhtkMk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'constat' => ['privates', '.errored..service_locator.zUhtkMk.App\\Entity\\Constat', NULL, 'Cannot autowire service ".service_locator.zUhtkMk": it references class "App\\Entity\\Constat" but no such service exists.'],
        ], [
            'constat' => 'App\\Entity\\Constat',
        ]);
    }
}
