<?php

namespace ContainerXFUFN6Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationType2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ReclamationType2' shared autowired service.
     *
     * @return \App\Form\ReclamationType2
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ReclamationType2'] = new \App\Form\ReclamationType2();
    }
}
