<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAeuE1Sx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAeuE1Sx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAeuE1Sx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAeuE1Sx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAeuE1Sx\App_KernelDevDebugContainer([
    'container.build_hash' => 'AeuE1Sx',
    'container.build_id' => 'fc0466e0',
    'container.build_time' => 1678311979,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAeuE1Sx');
